#!/bin/bash
## begin license ##
#
# "Metastreams Lucene" is a set of components and tools to integrate Lucene into Metastreams
#
# Copyright (C) 2021-2022 Seecr (Seek You Too B.V.) https://seecr.nl
#
# This file is part of "Metastreams Lucene"
#
# "Metastreams Lucene" is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# "Metastreams Lucene" is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with "Metastreams Lucene"; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
#
## end license ##

function show_usage {
    echo "Usage: $(basename $0)
    --target=<output path>
    --version=<meresco-lucene version>"
}

TEMP=$(getopt \
    --options "" \
    --long target::,version:: \
    -n "$0" -- "$@")

eval set -- "$TEMP"
while true
do
    case "$1" in
        --target)
            case "$2" in
                "") show_usage ; exit 1 ;;
                *) TARGET=$2 ; shift 2 ;;
            esac ;;
        --version)
            case "$2" in
                "") show_usage ; exit 1 ;;
                *) VERSION=$2 ; shift 2 ;;
            esac ;;
        --) shift ; break ;;
        *) echo "Unknown option specified." ; exit 1 ;;
    esac
done

set -o errexit
if [ -z "${TARGET}" -o -z "${VERSION}" ]; then
    show_usage
    exit 1
fi

mydir=$(cd $(dirname $0); pwd)
buildDir=$mydir/build

JAR_FILE=/usr/share/java/meresco-lucene/meresco-lucene-${VERSION}.jar
if [ ! -f "${JAR_FILE}" ]; then
    echo "{JAR_FILE} not found!"
    exit 1
fi

PYTHON=python3
pythonVersion=$(${PYTHON} --version 2>&1 | awk '{print $2}' | cut -d. -f-2)
pythonMajorVersion=$(${PYTHON} -c 'import sys; print(sys.version_info.major)')
pythonPackagesDir=/usr/lib64/python${pythonVersion}/site-packages
if [ -f /etc/debian_version ]; then
    pythonPackagesDir=/usr/lib/python${pythonMajorVersion}/dist-packages
fi

JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
if [ ! -d "${JAVA_HOME}" ]; then
    echo "${JAVA_HOME} does not exist"
    exit 0
fi

export JAVA_HOME
javac=${JAVA_HOME}/bin/javac

luceneJarDir=${pythonPackagesDir}/lucene

classpath=${luceneJarDir}/lucene-core-${LUCENE_VERSION}.jar:${luceneJarDir}/lucene-analyzers-common-${LUCENE_VERSION}.jar:${luceneJarDir}/lucene-facet-${LUCENE_VERSION}.jar:${luceneJarDir}/lucene-queries-${LUCENE_VERSION}.jar:${luceneJarDir}/lucene-misc-${LUCENE_VERSION}.jar

export CLASSPATH=${classpath}

test -d "${TARGET}" && rm -rf "${TARGET}"
test -d "${TARGET}" || mkdir "${TARGET}"

rm -rf $buildDir
mkdir --parents $buildDir

python3 -m jcc.__main__ \
    --include /usr/share/java/meresco-lucene/commons-math3-3.4.1.jar \
    --include /usr/share/java/meresco-lucene/javax.json-1.0.4.jar \
    --include /usr/share/java/meresco-lucene/commons-cli-1.2.jar \
    --include /usr/share/java/meresco-lucene/commons-collections4-4.1.jar \
    --include /usr/share/java/meresco-lucene/trove-3.0.2.jar \
    --shared \
    --use_full_names \
    --import lucene \
    --arch x86_64 \
    --jar ${JAR_FILE} \
    --exclude org.meresco.lucene.http.PrefixSearchHandler \
    --exclude org.meresco.lucene.http.AbstractMerescoLuceneHandler \
    --exclude org.meresco.lucene.http.NumerateHandler \
    --exclude org.meresco.lucene.http.ComposedQueryHandler \
    --exclude org.meresco.lucene.http.OtherHandler \
    --exclude org.meresco.lucene.http.QueryParameters \
    --exclude org.meresco.lucene.http.SettingsHandler \
    --exclude org.meresco.lucene.http.ExportKeysHandler \
    --exclude org.meresco.lucene.http.CommitHandler \
    --exclude org.meresco.lucene.http.LuceneHttpServer \
    --exclude org.meresco.lucene.http.UpdateHandler \
    --exclude org.meresco.lucene.http.DeleteHandler \
    --exclude org.meresco.lucene.http.QueryHandler \
    --exclude org.meresco.lucene.LuceneShutdown \
    --exclude org.meresco.lucene.suggestion.SuggestionHandler \
    --exclude org.meresco.lucene.suggestion.SuggestionShutdown \
    --exclude org.meresco.lucene.suggestion.SuggestionHttpServer \
    --python metastreams_lucene \
    --build \
    --install \
    --root "${TARGET}" \
